[package]
name = "reconnecting-jsonrpsee-ws-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"
jsonrpsee = { version = "0.20.1", features = ["ws-client"] }
serde_json = "1.0.107"
tokio = { version = "1.32.0", features = ["full"] }
tokio-retry = "0.3.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[dev-dependencies]
jsonrpsee = { version = "0.20.1", features = ["server"] }
anyhow = "1"